/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedBackground: typeof import('./src/components/AnimatedBackground.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    GlassShowcase: typeof import('./src/components/GlassShowcase.vue')['default']
    PropsPanel: typeof import('./src/components/PropsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFooter: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageBody: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue')['default']
    UPageHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USlider: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Slider.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.2.1_@babel+parse_393345e6409d3a57cd00cb7d9f064a48/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
